name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Lint
        run: go vet ./...

      - name: Run Unit Tests
        run: go test ./...

      - name: Build Application
        run: go build -v ./...

      - name: Run Security Scan
        run: go get -u github.com/securego/gosec/cmd/gosec && gosec ./...

  # Deployment job can be added here in the future
