name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.3'

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Lint
        run: go vet ./...

      - name: Run Unit Tests
        run: go test ./... -coverprofile=coverage.out

      - name: Build Application
        run: go build -v ./...

      - name: Run Security Scan
        run: go get -u github.com/securego/gosec/cmd/gosec && gosec ./...

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          MONGO_URI: ${{ secrets.MONGO_URI }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh
